#!/usr/bin/env python

import os
from subprocess import call

INPUT_DIR = 'resources'
OUTPUT_DIR = 'images'

def infile(filename):
    return os.path.join(INPUT_DIR, filename)

def outfile(filename):
    return os.path.join(OUTPUT_DIR, filename)

pages = [
    "page-clock.png",
    "page-layout-cv.png",
    "page-layout-gate.png",
    "page-layout-link.png",
    "page-layout-mode.png",
    "page-monitor-cv-in.png",
    "page-monitor-cv-out.png",
    "page-monitor-midi.png",
    "page-monitor-stats.png",
    "page-project.png",
    "page-routing-route.png",
    "page-routing.png",
    "page-sequence-edit.png",
    "page-sequence.png",
    "page-settings-cal.png",
    "page-settings-update.png",
    "page-song.png",
    "page-track.png",
    "page-user-scale.png",
]

# rescale page images
for filename in pages:
    print("resizing %s" % (filename))
    call(["convert", infile(filename), "-filter", "Box", "-resize", "512x128", outfile(filename)])

# create section images
def section_image(filename):
    call(["convert", infile("page-layout-mode.png"), "-filter", "Box", "-resize", "512x128", infile(filename), "-compose", "lighten", "-composite", outfile(filename)])

section_image("section-header.png")
section_image("section-main.png")
section_image("section-footer.png")
